# Configuración del plugin TimeLimit
# Este archivo se generará automáticamente al iniciar el plugin si no existe.

# Tiempo límite en segundos (por defecto son 4 horas)
timeLimit: 14400

# Texto para el mensaje de expulsión cuando se alcanza el tiempo límite (cambia las horas si cambiaste el tiempo límite)
kickMessage: "Has superado las 4 horas de juego. ¡Nos vemos mañana!"

# Texto para el mensaje de activación de la barra de tiempo
activateTimeMessage: "&a★ Tiempo activado"

# Texto para el mensaje de ocultación de la barra de tiempo
hideTimeMessage: "&c★ Tiempo ocultado"

# Texto para el mensaje de reinicio del tiempo de un jugador
resetTimeMessage: "&c★ Has reseteado el tiempo de juego de %player%."

# Texto para el mensaje de visualización del tiempo restante de un jugador
viewTimeMessage: "&b★ El tiempo restante de %player% es de %time%."

# Color de la barra de tiempo (bossbar)
# (BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW)
timeBarColor: "YELLOW"

# Estilo de la barra de tiempo (boosbar)
# (SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20)
timeBarStyle: "SEGMENTED_12"

# Jugadores a los que no les afectará el tiempo
infinite:
  - "ImPavloh"
  - "Notch"
  # Agrega más jugadores aquí
